feat(upload-sinan-dbf): include trigger to uploading files into dbf2/uploaded/
AlertaDengue/UpdateHistoricoAlerta pull request #17
Opened 2024-03-12 16:37 UTC by luabida

2024-03-12 16:51 UTC, esloch requested changes
Could you provide more information on how the command line is executed, for example?

2024-03-12 16:51 UTC, esloch commented on playbooks/upload-sinan-dbf.yaml
> +    HOST_FILE_PATH: "{{ DBF_HOST_DIR }}/{{ HOST_FILE_NAME }}"
```python
"{{ DBF_HOST_DIR }}/{{ DBF_NAME }}.dbf"
or
"{{ HOST_DIR }}/{{ DBF_NAME }}.dbf"
```

2024-03-12 16:51 UTC, esloch commented on playbooks/upload-sinan-dbf.yaml
> +        dest: "{{ REMOTE_TARGET_DIR }}/{{ HOST_FILE_NAME }}"
```python
 dest: "{{ REMOTE_TARGET_DIR }}/{{ DBF_NAME }}.dbf"
 ```

2024-03-12 16:55 UTC, luabida commented
> Could you provide more information on how the command line is executed, for example?

before the changes the commands were:
`makim ansible.upload-sinan-dbf --file test.txt --year 2024`
`makim ansible.history --logfile sinan_upload_dbf.log`

2024-03-12 19:17 UTC, luabida commented
@esloch 

command:
`makim ansible.upload-sinan-dbf --file-path /tmp/test.dbf --year 2024`

output:
`Tue Mar 12 04:10:30 PM -03 2024 ==> BR-DENG-2024-03-12-2024.dbf uploaded successfully`

2024-03-12 19:20 UTC, luabida commented
command:
`makim ansible.upload-sinan-dbf --file-path /tmp/test.dbf --year 2000 --codarea "SC" --disease "ZIKA"`

output:
`Tue Mar 12 04:20:02 PM -03 2024 ==> SC-ZIKA-2000-03-12-2024.dbf uploaded successfully`

2024-03-12 19:26 UTC, luabida commented
OBS: `file-path` can't be a relative path, it must be an absolute path

2024-03-13 10:00 UTC, esloch commented on playbooks/upload-sinan-dbf.yaml
> +
Please add the task to run the Django command `load_sinan`.

2024-03-13 15:40 UTC, esloch requested changes

2024-03-13 15:40 UTC, esloch commented on .makim.yaml
> +          case $DISEASE in CHIK) CID="A92.0";; ZIKA) CID="A92.5";; *) CID="A90";; esac
The correct CID10 code are:
`CID10 = {"dengue": "A90", "chikungunya": "A92.0", "zika": "A928"}`

2024-03-13 15:40 UTC, esloch commented on ansible/roles/sinan/scripts/upload_sinan.sh
> +    source /opt/environments/mambaforge/bin/activate alertadengue || {
Use the dev-alertadengue environment for just to keep the current version that works.

2024-03-13 17:48 UTC, esloch commented on playbooks/upload-sinan-dbf.yaml
> +      shell: "nohup /tmp/{{ SCRIPT }} /MEDIA_ROOT/{{ FILE_NAME }} {{ NOTIF_YEAR }} {{ CID }}"
If I'm not mistaken, the /MEDIA_ROOT/ is a volume in the web AlertaDengue container, not a directory in the root filesystem..

2024-03-13 21:42 UTC, luabida commented
ready to merge

2024-03-13 22:20 UTC, esloch approved these changes
Thank you, Bida, for working on that implementation. Could you proceed with the merge?

2024-03-13 22:53 UTC, merged